/**
 * Sole producer of all SQL aliases generated by the tree walker.
 *
 * Routing every alias through here guarantees uniqueness across the whole
 * compile (the counter lives on Context.cteCounter and is shared by every
 * recursive walk call).
 */

import type { Context } from "./types.js";

export function freshAlias(ctx: Context, prefix: string): string {
  const id = ctx.cteCounter.value++;
  return `${prefix}_${id}`;
}
